### PR TITLE
WebExtension-ish updated for TB128

### PR DESCRIPTION
**Pull request by jobisoft**
This is an WebExtension-ish update for TB128.

image

This pull request does the following:
* remove the old build process (because it did not work for me and made contributing difficult)
* convert the legacy locale strings to i18n json files
* remove the WindowListener API and use the dedicated [LegacyPrefs API](https://github.com/thunderbird/addon-developer-support/tree/master/auxiliary-apis/LegacyPrefs) to toggle the prefs
* use a browser_action button to toggle, instead of the status bar.

I cannot say at the moment if the prefs will ever be made available to be toggled by pure WebExtion, or if this will always need the LegacyPrefs API. But this update reduces the legacy dependencies to a minimum.

If you cannot accept the browser_action and must have the icon in the status bar, one could add a dedicated Experiment API for that as well, but we do suggest to work with the WebExtension UI elements.

### CODE REVIEW

**Comment by tomaszkrajewski** [comment]
Hi, thanks for contribution/help!!!!

1/ browser_action will work here, no pressure on having it in status bar.

2/ removing old build process - please let me know you to build now? Old process was established years ago, 3-4 PCs before current one, but for me it requires still only running ant & dist target in IntelliJ. Fully agree that it's overcomplicated, legacy, and no clue what is there, but still works and makes the package in the end;) For SubSwitch, when there is publicDist = true, then logining is reduced, when publicDist=false then there is a lot of debug in console (there were no other way to debug extensions 15 years ago... wow )

**Comment by jobisoft** [comment]
You now just have to zip the src folder :-)

For subswitch, we can solve this by using a LOG module, which is imported where needed. There is a way to detect debug mode and production mode which can be used to supress the logging.

**Comment by tomaszkrajewski** [comment]
c'mon, ant need to make the zip, but how about versioning?

**Comment by jobisoft** [comment]
I manually change the version in my manifests, when I release a new version. The version number does not need to be added anywhere else, so I never felt the need to have an automated process for new versions. I create the zip via context click on the folder. You can of course create scripts to do that. The important part however is to be able to use temporary install for fast development (where you do not create a zip, but hot-load your add-on from source) and that only works if the source itself is runnable without additional build steps.

But this is just a recommendation.

**Review by tomaszkrajewski — COMMENTED** [review]
can you please leave following ones:
.idea -> InteliJ
build.xml -> ant
project-moz.properties-> ant
build-moz-impl.xml -> ant
foxbeanstask.jar -> ant
tb-alertswitch-github.iml -> InteliJ

**Comment by jobisoft** [comment]
Done. These files need adjustments.

- we no longer have chrome files, pre-chrome, post-chrome and chrome-dir is not needed any more
- `foxbeanstask.jar`: consider unpacking the jar file or dropping it, due to recent supply-chain-attacks it is no longer recommended to have binary files in public open-source repos
- `project-moz.properties` has RDF content in `targetApplications` which is no longer needed
- `project-moz.properties` has `mozInstallationName` set to Mozilla Thunderbird 2
- `project-moz.properties` has `appdescription` which is now handled by the localisation system
- `build-moz-impl.xml` needs a complete overhaul

Last but not least: Keep it simple. Adding build instructions would help :-)

**Review by tomaszkrajewski — APPROVED** [review]

**Pull request merged**
